# Vehicle Types and Capacities
vehicles:
  A:
    capacity: 160
    fixed_cost: 100
  B:
    capacity: 0
    fixed_cost: 999
  C:
    capacity: 0
    fixed_cost: 999

# Cost Parameters
variable_cost_per_hour: 0.00

# Time Parameters
avg_speed: 40  # km/h
max_route_time: 100  # hours
service_time: 20  # minutes per customer

# Location
depot:
  latitude: 30.0
  longitude: 40.0

# Product Types
goods:
  - Dry
  - Chilled
  - Frozen

# Clustering Parameters
clustering:
  max_depth: 20
  method: minibatch_kmeans  # Options: minibatch_kmeans, kmedoids, agglomerative
  distance: euclidean  # Options: euclidean, composite (only for agglomerative)
  geo_weight: 1    # Weight for geographical distance (composite-only)
  demand_weight: 0  # Weight for demand distance (composite-only)
  route_time_estimation: 'Legacy'  # Options: Legacy, Clarke-Wright, BHH, CA, VRPSolver


# Data Files
# See options in /data
# sales_2023_high_demand_day
# sales_2023_low_demand_day
# sales_2023_uniform_visits_per_week
# sales_2023_avg_daily_demand -- WARNING: visits every client that ordered in the 9-month period
# sales_2023_09_avg_daily_demand -- WARNING: visits every client that ordered in September 2023
demand_file: "sales_2023_uniform_visits_per_week.csv"

# Math model Parameters
light_load_penalty: 0  # Adjust penalty value as needed -- 0 == don't penalize
light_load_threshold: 0.01  # Threshold for light load (e.g., 0.2 for 20%) -- when to penalize

# Results format
format: 'excel' # Options are 'excel' or 'json'