# Vehicle Types and Capacities
vehicles:
  A:
    capacity: 2700
    fixed_cost: 100
  B:
    capacity: 3300
    fixed_cost: 130
  C:
    capacity: 4500
    fixed_cost: 150

# Cost Parameters
variable_cost_per_km: 0.01

# Time Parameters
avg_speed: 40  # km/h
max_route_time: 10  # hours
service_time: 10  # minutes per customer

# Location
depot:
  latitude: 4.7
  longitude: -74.1

# Product Types
goods:
  - Dry
  - Chilled
  - Frozen

# Clustering Parameters
clustering:
  max_depth: 20
  method: MiniBatchKMeans 
  distance: 'euclidean' # Fixed for now
  route_time_estimation: '1hr + SERVICE_TIME_PER_CUSTOMER * num_customers in cluster' # Fixed for now

# Data Files
demand_file: "sales_2023_avg_daily_demand.csv" # See options in /data

# Math model
model_type: 2 # 1 = "Eric's" and 2 = "Fabri's"